/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RfqIndexRouteImport } from './routes/rfq.index'
import { Route as QuoteIndexRouteImport } from './routes/quote.index'
import { Route as RfqIdRouteImport } from './routes/rfq.$id'
import { Route as QuoteIdRouteImport } from './routes/quote.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqIndexRoute = RfqIndexRouteImport.update({
  id: '/rfq/',
  path: '/rfq/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteIndexRoute = QuoteIndexRouteImport.update({
  id: '/quote/',
  path: '/quote/',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqIdRoute = RfqIdRouteImport.update({
  id: '/rfq/$id',
  path: '/rfq/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteIdRoute = QuoteIdRouteImport.update({
  id: '/quote/$id',
  path: '/quote/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/quote/$id': typeof QuoteIdRoute
  '/rfq/$id': typeof RfqIdRoute
  '/quote/': typeof QuoteIndexRoute
  '/rfq/': typeof RfqIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/quote/$id': typeof QuoteIdRoute
  '/rfq/$id': typeof RfqIdRoute
  '/quote': typeof QuoteIndexRoute
  '/rfq': typeof RfqIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/quote/$id': typeof QuoteIdRoute
  '/rfq/$id': typeof RfqIdRoute
  '/quote/': typeof QuoteIndexRoute
  '/rfq/': typeof RfqIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/quote/$id' | '/rfq/$id' | '/quote/' | '/rfq/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/quote/$id' | '/rfq/$id' | '/quote' | '/rfq'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/quote/$id'
    | '/rfq/$id'
    | '/quote/'
    | '/rfq/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  QuoteIdRoute: typeof QuoteIdRoute
  RfqIdRoute: typeof RfqIdRoute
  QuoteIndexRoute: typeof QuoteIndexRoute
  RfqIndexRoute: typeof RfqIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq/': {
      id: '/rfq/'
      path: '/rfq'
      fullPath: '/rfq/'
      preLoaderRoute: typeof RfqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/': {
      id: '/quote/'
      path: '/quote'
      fullPath: '/quote/'
      preLoaderRoute: typeof QuoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq/$id': {
      id: '/rfq/$id'
      path: '/rfq/$id'
      fullPath: '/rfq/$id'
      preLoaderRoute: typeof RfqIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$id': {
      id: '/quote/$id'
      path: '/quote/$id'
      fullPath: '/quote/$id'
      preLoaderRoute: typeof QuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  QuoteIdRoute: QuoteIdRoute,
  RfqIdRoute: RfqIdRoute,
  QuoteIndexRoute: QuoteIndexRoute,
  RfqIndexRoute: RfqIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
